//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinhLam.Framework.Web
{


    public partial class AccountList
    {

        /// <summary>
        /// CustomGridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MinhLam.Framework.WebControls.CustomGridView CustomGridView1;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MinhLam.Framework.Web.EditGrid Master
        {
            get
            {
                return ((MinhLam.Framework.Web.EditGrid)(base.Master));
            }
        }
    }
}
